config/routes.rb
Rails.application.routes.draw do

  resources :users
 resources :suppliers  do
   resources :accounts do
    resource :account_histories
  end
  end

  resources :patients do
    resources :appointments
  end

  resources :physicians do 
    resources :appointments
  end
 end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :supplier
  has_one :account_history
end

app/models/account_history.rb
class AccountHistory < ApplicationRecord
belongs_to :account
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :physician
  belongs_to :patient
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
end

app/models/passport.rb
class Passport < ApplicationRecord
  belongs_to :person
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :appointments
  has_many :physicians, through: :appointments
end

app/models/person.rb
class Person < ApplicationRecord
  has_many :passports
end

app/models/physician.rb
class Physician < ApplicationRecord
  has_many :appointments
  has_many :patients, through: :appointments
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  has_one :account
  has_one :account_history, through: :account
end

app/models/user.rb
class User < ApplicationRecord
  has_and_belongs_to_many :roles
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def index
    @accounts =  Account.all
  end
  def new
    @supplier= Supplier.find(params[:supplier_id])
    @account=@supplier.build_account

  end
  def show
    @supplier= Supplier.find(params[:supplier_id])
    @account= Account.find(params[:id])
end
def create
  @supplier= Supplier.find(params[:supplier_id])
  @account=@supplier.build_account(params.require(:account).permit(:account_number))
  if @account.save
    redirect_to supplier_account_path(@supplier, @account)
  else
    render 'new_supplier_account'
  end
end
def destroy
    @account=Account.find(params[:id])
    @account.destroy
    redirect_to suppliers_path
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  def index
    @patients= Patient.all
  end
  def show
    @patient= Patient.find(params[:id]) 
      end
 def new
  @patient= Patient.new
 end
 def create
  @patient= Patient.create(params.require(:patient).permit(:name))
  if @patient.save
    redirect_to @patient
  else 
    render "new_patient"
 end
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
       @user= User.find(params[:id]) 
  end

  # GET /users/new
  def new
    @user = User.new()
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.create(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
  
      def user_params
      params.require(:user).permit(:name, role_ids:[])
 
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/accounts/index.html.erb
<h1>Accounts</h1>

<ul>
  <% @accounts.each do |account| %>
    <li>
      <%= account.account_number %>
    </li>
  <% end %>
</ul>

app/views/accounts/new.html.erb
<%= form_for @account, url: supplier_accounts_path(@supplier), method: :post  do |form|%>
  <%= form.label :account_number %>
  <%= form.text_field :account_number %>
  <%= form.submit %>
<% end %>

app/views/accounts/show.html.erb
<h1><%= @account.account_number%></h1>
<%= link_to "Delete Account", supplier_account_path(@supplier, @account), method: :delete%>

app/views/patients/index.html.erb
<h2>I am patient</h2>

app/views/patients/new.html.erb
<h2> form of Patients</h2> 
<%= form_for @patient, url: {action: "create"} do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>
  <%= form.submit %>
<% end %>

app/views/patients/show.html.erb
<h2>Show Patient name</h2>
<h2><%= @patient.name %> </h2>
<%= link_to "Create Appointment", new_patient_appointment_path(@patient)%>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div>
  <%=form.label :name, "User name" %>
   <%=form.text_field :name %>
   <%= form.collection_check_boxes(:role_ids, Role.all,:id, :title) %>
</div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>

      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<%= @user.name %>
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>